name: manual-ci

on:
  workflow_dispatch:
    inputs:
      name:
      description: 'This is an input workflow'
      default: 'hello world'
      required: true

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:

      - name: Send greeting
        run: echo "This is the greeting you asked for: ${{ github.event.inputs.name }}"
